version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: my-nginx-container
    ports:
      - "8080:80"  # Bind port 80 in the container to port 8080 on the host
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Mount your custom nginx.conf file
      - ./index.html:/usr/share/nginx/html/index.html  # Mount your custom index.html
    restart: always  # Ensures the container restarts automatically if it crashes
